title: Site for answer questions
email: lanolin26@github.io
description: >-
  Ответы на вопросы
baseurl: "/"
url: https://lanolin26.github.io
domain: lanolin26.github.io

theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - kramdown
  - liquid

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
